# Generated by Django 5.1.7 on 2025-03-18 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Varna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varna_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_word', models.CharField(max_length=100)),
                ('details', models.JSONField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.source')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.type')),
                ('varna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.varna')),
            ],
        ),
    ]
